//
//  Product.swift
//  Kmeza
//
//  Created by Pavel Anpleenko on 12.01.2021.
//

struct Product {
	let cover: String
	let typeCollection: String
	let productType: String
	let name: String
	let price: Double
	let sale: Double
	let numberStock: Int
	let numberOfProducts: Int
	let productInformation: InformationOfProduct
	
	static let products: [Product] = [
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Man collections",
			  productType: "Discover",
			  name: "1Dis_Denim Jacket",
			  price: 56.00,
			  sale: 60.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_1"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_1"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_3")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Shoes"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "XXL")])), //"Discover"
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Man collections",
			  productType: "Discover",
			  name: "2Dis_Denim Jacket",
			  price: 56.00,
			  sale: 60.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Suits"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "XL")])), //"Discover"
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Man collections",
			  productType: "Discover",
			  name: "3Dis_Denim Jacket",
			  price: 56.00,
			  sale: 60.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Dress"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "XXL")])), //"Discover"
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Man collections",
			  productType: "Discover",
			  name: "4Dis_Denim Jacket",
			  price: 56.00,
			  sale: 60.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Dress"),
													   sizes: [Size(size: "S"),
															   Size(size: "L"),
															   Size(size: "XL")])), //"Discover"
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Man collections",
			  productType: "Discover",
			  name: "5Dis_1Denim Jacket",
			  price: 56.00,
			  sale: 60.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Dress"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Discover"
		.init(cover: "Walkthrough_Screen_2",
			  typeCollection: "Woman collections",
			  productType: "Flash Sale",
			  name: "1FS_Denim Jhins",
			  price: 123.46,
			  sale: 150.00,
			  numberStock: 200,
			  numberOfProducts: 100,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3")],
													   numberOfReviews: 4512,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Suits"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "XXL")])), //"Flash Sale"
		.init(cover: "Walkthrough_Screen_2",
			  typeCollection: "Woman collections",
			  productType: "Flash Sale",
			  name: "2Denim Jhins",
			  price: 123.46,
			  sale: 150.00,
			  numberStock: 200,
			  numberOfProducts: 100,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3")],
													   numberOfReviews: 4512,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Suits"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "XXL")])), //"Flash Sale"
		.init(cover: "Walkthrough_Screen_2",
			  typeCollection: "Woman collections",
			  productType: "Flash Sale",
			  name: "2Denim Jhins",
			  price: 123.46,
			  sale: 150.00,
			  numberStock: 200,
			  numberOfProducts: 115,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_1"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_1")],
													   numberOfReviews: 4512,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Dress"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "XXL")])), //"Flash Sale"
		.init(cover: "Walkthrough_Screen_2",
			  typeCollection: "Woman collections",
			  productType: "Flash Sale",
			  name: "2Denim Jhins",
			  price: 123.46,
			  sale: 150.00,
			  numberStock: 200,
			  numberOfProducts: 120,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3")],
													   numberOfReviews: 4512,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Suits"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Flash Sale"
		.init(cover: "Walkthrough_Screen_2",
			  typeCollection: "Woman collections",
			  productType: "Flash Sale",
			  name: "2Denim Jhins",
			  price: 123.46,
			  sale: 150.00,
			  numberStock: 200,
			  numberOfProducts: 1,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3")],
													   numberOfReviews: 4512,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Suits"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Flash Sale"
		.init(cover: "Walkthrough_Screen_2",
			  typeCollection: "Woman collections",
			  productType: "Flash Sale",
			  name: "2Denim Jhins",
			  price: 123.46,
			  sale: 150.00,
			  numberStock: 200,
			  numberOfProducts: 200,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3")],
													   numberOfReviews: 4512,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Suits"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Flash Sale"
		.init(cover: "Walkthrough_Screen_2",
			  typeCollection: "Woman collections",
			  productType: "Flash Sale",
			  name: "7FS_Denim Jhins",
			  price: 123.46,
			  sale: 150.00,
			  numberStock: 200,
			  numberOfProducts: 200,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3"),
																	ProductImage(image: "Walkthrough_Screen_3")],
													   numberOfReviews: 4512,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Suits"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Flash Sale"
		.init(cover: "Walkthrough_Screen_3",
			  typeCollection: "Woman collections",
			  productType: "Newest Products",
			  name: "1Ne_Denim Tishort",
			  price: 800.99,
			  sale: 1200.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_1"),
																	ProductImage(image: "Walkthrough_Screen_1"),
																	ProductImage(image: "Walkthrough_Screen_1"),
																	ProductImage(image: "Walkthrough_Screen_1"),
																	ProductImage(image: "Walkthrough_Screen_1"),
																	ProductImage(image: "Walkthrough_Screen_1")],
													   numberOfReviews: 1234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Shoes"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Newest Products"
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Woman collections",
			  productType: "Newest Products",
			  name: "4Denim Jacket",
			  price: 1523.46,
			  sale: 1600.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Shoes"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Newest Products"
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Woman collections",
			  productType: "Newest Products",
			  name: "4Denim Jacket",
			  price: 1523.46,
			  sale: 1600.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Shoes"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Newest Products"
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Woman collections",
			  productType: "Newest Products",
			  name: "4Denim Jacket",
			  price: 1523.46,
			  sale: 1600.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Dress"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")])), //"Newest Products"
		.init(cover: "Walkthrough_Screen_1",
			  typeCollection: "Woman collections",
			  productType: "Newest Products",
			  name: "5Ne_Denim Jacket",
			  price: 1523.46,
			  sale: 1600.00,
			  numberStock: 123,
			  numberOfProducts: 0,
			  productInformation: InformationOfProduct(thumbnails: [ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2"),
																	ProductImage(image: "Walkthrough_Screen_2")],
													   numberOfReviews: 234,
													   description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et",
													   colorPickers: [ColorPicker(red: 0.92,
																				  green: 0.20,
																				  blue: 0.14),
																	  ColorPicker(red: 0.46,
																				  green: 0.98,
																				  blue: 0.30),
																	  ColorPicker(red: 1.00,
																				  green: 0.60,
																				  blue: 0.49),
																	  ColorPicker(red: 1.00,
																				  green: 1.00,
																				  blue: 0.33),
																	  ColorPicker(red: 0.31,
																				  green: 0.32,
																				  blue: 0.33)],
													   specification: Specification(brand: "Naiki Shoes",
																					weight: "260gr",
																					condition: "NEW",
																					category: "Men Cloths",
																					typeCloths: "Dress"),
													   sizes: [Size(size: "S"),
															   Size(size: "M"),
															   Size(size: "L"),
															   Size(size: "Xl"),
															   Size(size: "XXL")]))  //"Newest Products"
	]
	
	static func sortFetchData(by type: ProductType) -> [Product] {
		var products: [Product] = []
		
		Product.products.forEach { (product) in
			if product.productType == type.rawValue {
				let product = Product(cover: product.cover,
									  typeCollection: product.typeCollection,
									  productType: product.productType,
									  name: product.name,
									  price: product.price,
									  sale: product.sale,
									  numberStock: product.numberStock,
									  numberOfProducts: product.numberOfProducts,
									  productInformation: product.productInformation)
				products.append(product)
			}
		}
		
		return products
	}
}


enum ProductType: String {
	case discover = "Discover"
	case flashSale = "Flash Sale"
	case newestProducts = "Newest Products"
}
